
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadgrupo1.vistas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidadgrupo1.AccesoADatos.AlumnoData;
import universidadgrupo1.AccesoADatos.InscripcionData;
import universidadgrupo1.AccesoADatos.MateriaData;
import universidadgrupo1.entidades.Alumno;
import universidadgrupo1.entidades.Materia;
/**
 *
 * @author tadeowoto
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    private ArrayList<Materia> listaMat;
    private ArrayList<Alumno> listaAlum;
    
    private InscripcionData inscData;
    private MateriaData matData;
    private AlumnoData alumData;
    
    private DefaultTableModel model;
    
    public FormularioInscripcion() {
        initComponents();

        alumData = new AlumnoData();
        matData = new MateriaData();
        inscData = new InscripcionData();
        model = new DefaultTableModel();
        listaAlum = (ArrayList<Alumno>) alumData.listarAlumnos(); //tambien se puede hacer con List
        armarCabecera();
        cargarAlumnos();//carga el combo box con los alumnos del metodo listar alumnos
        
    }
    public void borrarFilas() {
        int i = model.getRowCount();

        for (int j = i-1; j >= 0; j--) {
            model.removeRow(j);
        }

    }
    
    private void armarCabecera(){
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Id");
        filaCabecera.add("Nombre");
        filaCabecera.add("Anio");
        
        for (Object i : filaCabecera) {
            model.addColumn(i);
        }
        tblListadoAlumnos.setModel(model);
    }

    private void cargarAlumnos(){
        for (Alumno item : listaAlum) {
            cbAlumno.addItem(item);
        }
    }
    
    private void cargaDatosInsc(){
        Alumno select = (Alumno) cbAlumno.getSelectedItem();
        listaMat = (ArrayList<Materia>) inscData.obtenerMateriasCursadas(select.getIdAlumno());
        for (Materia mat : listaMat) {
            model.addRow(new Object[] {mat.getIdMateria(),mat.getNombre(), mat.getAnio()});
        }
        
    }
    
    private void cargaDatosNoInsc(){
        
        Alumno select = (Alumno) cbAlumno.getSelectedItem();
        listaMat = (ArrayList<Materia>) inscData.obtenerMateriasNoCursadas(select.getIdAlumno());
        
        for (Materia mat : listaMat) {
            model.addRow(new Object[] {mat.getIdMateria(),mat.getNombre(),mat.getAnio()});
        }
        
    } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSeleccionarAlumno = new javax.swing.JLabel();
        cbAlumno = new javax.swing.JComboBox<>();
        lblListMaterias = new javax.swing.JLabel();
        rbtnMateriasInsc = new javax.swing.JRadioButton();
        rbtnMateriasNoInsc = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoAlumnos = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitulo.setText("Inscripciones");

        lblSeleccionarAlumno.setText("Seleccione un Alumno:");

        lblListMaterias.setText("Listado de Materias ");

        rbtnMateriasInsc.setText("Materias inscriptas");
        rbtnMateriasInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMateriasInscActionPerformed(evt);
            }
        });

        rbtnMateriasNoInsc.setText("Materias no inscriptas");
        rbtnMateriasNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMateriasNoInscActionPerformed(evt);
            }
        });

        tblListadoAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoAlumnos);

        btnInscribir.setText("Inscribir");
        btnInscribir.setEnabled(false);

        btnAnular.setText("Anular Inscripcion");
        btnAnular.setEnabled(false);

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeleccionarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbtnMateriasInsc)
                            .addGap(92, 92, 92)
                            .addComponent(rbtnMateriasNoInsc))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(lblListMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInscribir)
                                .addGap(43, 43, 43)
                                .addComponent(btnAnular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblListMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnMateriasInsc)
                    .addComponent(rbtnMateriasNoInsc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnular)
                    .addComponent(btnSalir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMateriasInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMateriasInscActionPerformed
        borrarFilas();
        rbtnMateriasNoInsc.setSelected(false); //deja al otro boton inutil
        cargaDatosInsc();
        btnAnular.setEnabled(true);
        btnInscribir.setEnabled(false);
    }//GEN-LAST:event_rbtnMateriasInscActionPerformed

    private void rbtnMateriasNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMateriasNoInscActionPerformed
        borrarFilas();
        rbtnMateriasInsc.setSelected(false); //deja al otro boton inutil
        cargaDatosNoInsc();
        btnAnular.setEnabled(false);
        btnInscribir.setEnabled(true);
    }//GEN-LAST:event_rbtnMateriasNoInscActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnular;
    public javax.swing.JButton btnInscribir;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<Alumno> cbAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListMaterias;
    private javax.swing.JLabel lblSeleccionarAlumno;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JRadioButton rbtnMateriasInsc;
    public javax.swing.JRadioButton rbtnMateriasNoInsc;
    public javax.swing.JTable tblListadoAlumnos;
    // End of variables declaration//GEN-END:variables
}


