/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo1.Vistas;

/**
 *
 * @author amiev
 */
public class MGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MGeneral
     */
    public MGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpGeneral = new javax.swing.JDesktopPane();
        ifFormAlumno = new javax.swing.JInternalFrame();
        lblTitulo = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        btnNuevoAlum = new javax.swing.JButton();
        btnEliminarAlum = new javax.swing.JButton();
        btnGuardarAlum = new javax.swing.JButton();
        btnSalirAlum = new javax.swing.JButton();
        btnBuscarAlum = new javax.swing.JButton();
        tfDocumento = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        rbEstado = new javax.swing.JRadioButton();
        infMateria = new javax.swing.JInternalFrame();
        lblTituloMat = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btnBuscarMat = new javax.swing.JButton();
        lblAño = new javax.swing.JLabel();
        tfAño = new javax.swing.JTextField();
        lblNombreMat = new javax.swing.JLabel();
        tfNombreMat = new javax.swing.JTextField();
        lblEstadoMat = new javax.swing.JLabel();
        rbEstadoMat = new javax.swing.JRadioButton();
        btnNuevaMat = new javax.swing.JButton();
        btnEliminarMat = new javax.swing.JButton();
        btnGuardarMat = new javax.swing.JButton();
        btnSalirMat = new javax.swing.JButton();
        ifAlumnosPorMateria = new javax.swing.JInternalFrame();
        lblTituloListado = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox<>();
        spTabla = new javax.swing.JScrollPane();
        tblInscriptos = new javax.swing.JTable();
        btnSalirListado = new javax.swing.JButton();
        mbMenuGeneral = new javax.swing.JMenuBar();
        mAlumno = new javax.swing.JMenu();
        miFormAlumno = new javax.swing.JMenuItem();
        mMateria = new javax.swing.JMenu();
        miFormMateria = new javax.swing.JMenuItem();
        mAdministracion = new javax.swing.JMenu();
        miInscripciones = new javax.swing.JMenuItem();
        miNotas = new javax.swing.JMenuItem();
        mConsultas = new javax.swing.JMenu();
        miConsultaAlumnos = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ifFormAlumno.setVisible(true);

        lblTitulo.setText("Alumno");

        lblDocumento.setText("Documento:");

        lblApellido.setText("Apellido:");

        lblNombre.setText("Nombre:");

        lblEstado.setText("Estado:");

        lblFechaNac.setText("Fecha de Nacimiento:");

        btnNuevoAlum.setText("Nuevo");

        btnEliminarAlum.setText("Eliminar");

        btnGuardarAlum.setText("Guardar");

        btnSalirAlum.setText("Salir");

        btnBuscarAlum.setText("Buscar");

        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifFormAlumnoLayout = new javax.swing.GroupLayout(ifFormAlumno.getContentPane());
        ifFormAlumno.getContentPane().setLayout(ifFormAlumnoLayout);
        ifFormAlumnoLayout.setHorizontalGroup(
            ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                                    .addComponent(lblDocumento)
                                    .addGap(31, 31, 31)
                                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblApellido)
                                .addComponent(lblNombre)
                                .addComponent(lblEstado))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarAlum))
                        .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbEstado)
                                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNombre)
                                    .addComponent(lblTitulo)
                                    .addComponent(tfApellido)))))
                    .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                        .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaNac)
                            .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                                .addComponent(btnNuevoAlum)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarAlum)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarAlum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirAlum)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ifFormAlumnoLayout.setVerticalGroup(
            ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifFormAlumnoLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(rbEstado))
                .addGap(30, 30, 30)
                .addComponent(lblFechaNac)
                .addGap(18, 18, 18)
                .addGroup(ifFormAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAlum)
                    .addComponent(btnEliminarAlum)
                    .addComponent(btnGuardarAlum)
                    .addComponent(btnSalirAlum))
                .addGap(83, 83, 83))
        );

        infMateria.setVisible(true);

        lblTituloMat.setText("Materia");

        lblCodigo.setText("Codigo");

        btnBuscarMat.setText("Buscar");

        lblAño.setText("Año");

        tfAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAñoActionPerformed(evt);
            }
        });

        lblNombreMat.setText("Nombre:");

        lblEstadoMat.setText("Estado:");

        btnNuevaMat.setText("Nuevo");

        btnEliminarMat.setText("Eliminar");

        btnGuardarMat.setText("Guardar");

        btnSalirMat.setText("Salir");

        javax.swing.GroupLayout infMateriaLayout = new javax.swing.GroupLayout(infMateria.getContentPane());
        infMateria.getContentPane().setLayout(infMateriaLayout);
        infMateriaLayout.setHorizontalGroup(
            infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infMateriaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infMateriaLayout.createSequentialGroup()
                                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo)
                                    .addComponent(lblEstadoMat))
                                .addGap(60, 60, 60)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarMat))
                            .addGroup(infMateriaLayout.createSequentialGroup()
                                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreMat)
                                    .addComponent(lblAño))
                                .addGap(51, 51, 51)
                                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbEstadoMat)
                                    .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfNombreMat)
                                        .addComponent(lblTituloMat)
                                        .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(infMateriaLayout.createSequentialGroup()
                        .addComponent(btnNuevaMat)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirMat)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        infMateriaLayout.setVerticalGroup(
            infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(btnBuscarMat))
                    .addComponent(tfCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreMat))
                .addGap(10, 10, 10)
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAño))
                .addGap(18, 18, 18)
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoMat)
                    .addComponent(rbEstadoMat))
                .addGap(64, 64, 64)
                .addGroup(infMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaMat)
                    .addComponent(btnEliminarMat)
                    .addComponent(btnGuardarMat)
                    .addComponent(btnSalirMat))
                .addGap(61, 61, 61))
        );

        ifAlumnosPorMateria.setVisible(true);

        lblTituloListado.setText("Listado de Alumnos por Materia");

        lblSeleccion.setText("Seleccione una materia");

        tblInscriptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Dni", "Apellido", "Nombre"
            }
        ));
        spTabla.setViewportView(tblInscriptos);

        btnSalirListado.setText("Salir");

        javax.swing.GroupLayout ifAlumnosPorMateriaLayout = new javax.swing.GroupLayout(ifAlumnosPorMateria.getContentPane());
        ifAlumnosPorMateria.getContentPane().setLayout(ifAlumnosPorMateriaLayout);
        ifAlumnosPorMateriaLayout.setHorizontalGroup(
            ifAlumnosPorMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifAlumnosPorMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ifAlumnosPorMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ifAlumnosPorMateriaLayout.createSequentialGroup()
                        .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifAlumnosPorMateriaLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(ifAlumnosPorMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifAlumnosPorMateriaLayout.createSequentialGroup()
                                .addComponent(lblTituloListado)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifAlumnosPorMateriaLayout.createSequentialGroup()
                                .addComponent(spTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifAlumnosPorMateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirListado)
                .addContainerGap())
        );
        ifAlumnosPorMateriaLayout.setVerticalGroup(
            ifAlumnosPorMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifAlumnosPorMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloListado)
                .addGap(24, 24, 24)
                .addGroup(ifAlumnosPorMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccion)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnSalirListado))
        );

        dpGeneral.setLayer(ifFormAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpGeneral.setLayer(infMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpGeneral.setLayer(ifAlumnosPorMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpGeneralLayout = new javax.swing.GroupLayout(dpGeneral);
        dpGeneral.setLayout(dpGeneralLayout);
        dpGeneralLayout.setHorizontalGroup(
            dpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpGeneralLayout.createSequentialGroup()
                .addGroup(dpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpGeneralLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ifFormAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(infMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ifAlumnosPorMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        dpGeneralLayout.setVerticalGroup(
            dpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpGeneralLayout.createSequentialGroup()
                .addGroup(dpGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpGeneralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ifFormAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpGeneralLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(infMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addComponent(ifAlumnosPorMateria)
                .addGap(65, 65, 65))
        );

        mAlumno.setText("Alumno");

        miFormAlumno.setText("Formulario de alumno");
        miFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormAlumnoActionPerformed(evt);
            }
        });
        mAlumno.add(miFormAlumno);

        mbMenuGeneral.add(mAlumno);

        mMateria.setText("Materia");

        miFormMateria.setText("Formulario materia");
        mMateria.add(miFormMateria);

        mbMenuGeneral.add(mMateria);

        mAdministracion.setText("Administracion");

        miInscripciones.setText("Manejo de inscripciones");
        mAdministracion.add(miInscripciones);

        miNotas.setText("Manipulacion de notas");
        mAdministracion.add(miNotas);

        mbMenuGeneral.add(mAdministracion);

        mConsultas.setText("Consultas");

        miConsultaAlumnos.setText("Alumnos por materia");
        mConsultas.add(miConsultaAlumnos);

        mbMenuGeneral.add(mConsultas);

        mSalir.setText("Salir");
        mbMenuGeneral.add(mSalir);

        setJMenuBar(mbMenuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpGeneral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miFormAlumnoActionPerformed

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlum;
    private javax.swing.JButton btnBuscarMat;
    private javax.swing.JButton btnEliminarAlum;
    private javax.swing.JButton btnEliminarMat;
    private javax.swing.JButton btnGuardarAlum;
    private javax.swing.JButton btnGuardarMat;
    private javax.swing.JButton btnNuevaMat;
    private javax.swing.JButton btnNuevoAlum;
    private javax.swing.JButton btnSalirAlum;
    private javax.swing.JButton btnSalirListado;
    private javax.swing.JButton btnSalirMat;
    private javax.swing.JComboBox<String> cbMateria;
    private javax.swing.JDesktopPane dpGeneral;
    private javax.swing.JInternalFrame ifAlumnosPorMateria;
    private javax.swing.JInternalFrame ifFormAlumno;
    private javax.swing.JInternalFrame infMateria;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoMat;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreMat;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloListado;
    private javax.swing.JLabel lblTituloMat;
    private javax.swing.JMenu mAdministracion;
    private javax.swing.JMenu mAlumno;
    private javax.swing.JMenu mConsultas;
    private javax.swing.JMenu mMateria;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuBar mbMenuGeneral;
    private javax.swing.JMenuItem miConsultaAlumnos;
    private javax.swing.JMenuItem miFormAlumno;
    private javax.swing.JMenuItem miFormMateria;
    private javax.swing.JMenuItem miInscripciones;
    private javax.swing.JMenuItem miNotas;
    private javax.swing.JRadioButton rbEstado;
    private javax.swing.JRadioButton rbEstadoMat;
    private javax.swing.JScrollPane spTabla;
    private javax.swing.JTable tblInscriptos;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfAño;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDocumento;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreMat;
    // End of variables declaration//GEN-END:variables
}
